version: '3.8'

services:
  app:
    build:
      context: .            
      dockerfile: Dockerfile
    image: sai-travels
    ports:
      - "3000:3000"      
    environment:
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}            
      - NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${NEXT_PUBLIC_STRIPE_PUBLIC_KEY}      
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY} 
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - mongo

  mongo:
    image: mongo:6          
    ports:
      - "27017:27017"       
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:              
