import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NextAuthProvider } from "./Providers";

import { Toaster } from "@/components/ui/toaster";
import '../server/cron'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sai Bus Travles",
  description: "Generated by Tushar Bajaj",
  icons:{
    icon:['/favicon.ico?v=4']
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}
            <Toaster />
          </body>
        </html>
    </NextAuthProvider>
  );
}
