import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/server/footer";
import { NextAuthProvider } from "./Providers";
import { ToastProvider } from "@radix-ui/react-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sai Bus Travles",
  description: "Generated by Tushar Bajaj",
  icons:{
    icon:['/favicon.ico?v=4']
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
      <ToastProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}
            <Footer />
          </body>
        </html>
      </ToastProvider>
    </NextAuthProvider>
  );
}
